title: Lucky's Walk-In
description: >-
  Luckyâ€™s Walk-In is a community-driven initiative dedicated to empowering 
  individuals on their journey to a fresh start. We provide professional 
  attire, confidence-building resources, and a supportive environment.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Navigation links for your header
header_pages:
  - index.md
  - mission.md
  - stories.md
  - inventory.md
  - support.md
  - contact.md

# Tells Jekyll to look for your inventory data
data_dir: _data
