title: Lucky's Walk-In
description: >-
  Luckyâ€™s Walk-In is a community-driven initiative dedicated to empowering 
  individuals on their journey to a fresh start. We provide professional 
  attire, confidence-building resources, and a supportive environment for 
  those seeking second chances in the workforce.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# This line is the "Secret Sauce" for your inventory
data_dir: _data
